// import React from "react";

// import { Metadata } from "next";
// import SignUp from "./components/SignUp";

// export const metadata: Metadata = {
//   title: "SignUp || BlogPlex",
//   description: "Generated by create BlogPlex",
// };

// const SignUpPage = () => {
//   return (
//     <div>
//       <SignUp />
//     </div>
//   );
// };

// export default SignUpPage;



// import React from 'react'

// import { Metadata } from 'next';
// import SignIn from './components/SignIn';

// export const metadata: Metadata = {
//   title: "SignIn || BlogPlex ",
//   description: 'An BlogPlex built with Next.js, Postgres, Shadcn signin'
// };

// const SignInPage = () => {
//   return (
//     <div className='wrapper'>
//       <SignIn/>
//     </div>
//   )
// }

// export default SignInPage

import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs"

import SignUp from "../signup/components/SignUp"

import { Metadata } from 'next';
import SignIn from "../signin/components/SignIn";
import AddBlogForm from "@/components/Form/AddBlogForm";
import CreateAuthorForm from "@/components/Form/AuthorCreateForm";
import BloggerRegister from "./components/BloggerRegister";


export const metadata: Metadata = {
  title: "SignUp || BlogPlex ",
  description: 'An BlogPlex built with Next.js, Postgres, Shadcn signin'
};

const  SignUpPage=()=> {
  return (
    <div className="flex justify-center items-center mx-auto p-10">
      <Tabs
        orientation="vertical"
        defaultValue="signin"
        className="w-[1000px] "
      >
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="signin">Sign In</TabsTrigger>
          <TabsTrigger value="signup">Sign Up</TabsTrigger>
        </TabsList>
        <TabsContent value="signin">
          <BloggerRegister />
        </TabsContent>
        <TabsContent value="signup">
          <SignUp />
        </TabsContent>
      </Tabs>
    </div>
  );
}

export default SignUpPage

