import React from "react";

import { Metadata } from "next";
import SignUp from "./components/SignUp";


export const metadata: Metadata = {
  title: "SignUp || BlogPlex",
  description: "Generated by create BlogPlex",
};

const SignUpPage = () => {
  return (
    <div>
      <SignUp />
    </div>
  );
};

export default SignUpPage;