import React from 'react';
import { Dashboard } from '@/components/Dashboard/Dashboard';
import { Metadata } from 'next';
import { USER_ROLE } from '@/constants/role';
import { TagDashboard } from '@/components/Dashboard/TagDashboard';

export const metadata: Metadata = {
  title: 'dashboard || blogPlex',
  description: 'Generated by create next app',
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <TagDashboard>{children}</TagDashboard>
    </div>
  );
};

export default DashboardLayout;
