import React from 'react';
import { Dashboard } from '@/components/Dashboard/Dashboard';
import { Metadata } from 'next';
import { USER_ROLE } from '@/constants/role';

export const metadata: Metadata = {
  title: "ShareNest App || dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode}) => {
  return (
    <div>
      <Dashboard>
        {children}
      </Dashboard>
    </div>
  );
};

export default DashboardLayout;
